/**
 * reports.js — MilkBook v2
 * CSV export and report text generation.
 */

import { formatCurrency, getMonthName, calcMonthlyTotals } from './calculations.js';

/** Download a monthly CSV for a single customer. */
export function downloadCustomerCSV(customer, records, month, year, rate) {
    const monthName = getMonthName(month);
    const filename = `MilkBook_${(customer.name || 'customer').replace(/\s+/g, '_')}_${monthName}_${year}.csv`;

    let csv = `MilkBook — Milk Delivery Report\n`;
    csv += `Customer: ${customer.name}\n`;
    csv += `Phone: ${customer.phone || '—'}\n`;
    csv += `Period: ${monthName} ${year}\n\n`;

    csv += `Date,Day,Session,Quantity (L),Rate,Amount (₹)\n`;

    const sorted = [...records].sort((a, b) => a.date.localeCompare(b.date));
    let totalLitres = 0, totalAmount = 0;

    for (const rec of sorted) {
        if (rec.no_delivery) continue;
        const d = new Date(rec.date);
        const dayName = d.toLocaleDateString('en-IN', { weekday: 'short' });

        // Morning
        if (rec.morning_qty > 0) {
            csv += `${rec.date},${dayName},Morning,${rec.morning_qty},${rec.rate_per_litre || rate},${(rec.morning_qty * (rec.rate_per_litre || rate)).toFixed(2)}\n`;
        }
        // Evening
        if (rec.evening_qty > 0) {
            csv += `${rec.date},${dayName},Evening,${rec.evening_qty},${rec.rate_per_litre || rate},${(rec.evening_qty * (rec.rate_per_litre || rate)).toFixed(2)}\n`;
        }

        totalLitres += (parseFloat(rec.total_litres) || 0);
        totalAmount += (parseFloat(rec.daily_amount) || 0);
    }

    csv += `\nTOTAL,,, ${totalLitres.toLocaleString('en-IN', { maximumFractionDigits: 3 })} L,, ${totalAmount.toFixed(2)}\n`;
    csv += `\nGenerated by MilkBook on ${new Date().toLocaleDateString('en-IN')}\n`;

    triggerDownload(csv, filename);
}

/** Download a full CSV summary for all customers. */
export function downloadAllCSV(allData, month, year, rate) {
    const monthName = getMonthName(month);
    const filename = `MilkBook_Summary_${monthName}_${year}.csv`;

    let csv = `MilkBook Business Summary — ${monthName} ${year}\n\n`;
    csv += `Customer Name,Phone,Days Delivered,Total Litres,Gross Bill (₹),Paid (₹),Outstanding (₹)\n`;

    let grandLitres = 0, grandAmount = 0, grandPaid = 0;

    for (const row of allData) {
        csv += `"${row.name}","${row.phone || '—'}",${row.totals.daysDelivered},${row.totals.totalLitres},${row.totals.totalAmount.toFixed(2)},${row.paidAmt.toFixed(2)},${row.outstanding.toFixed(2)}\n`;
        grandLitres += row.totals.totalLitres;
        grandAmount += row.totals.totalAmount;
        grandPaid += row.paidAmt;
    }

    csv += `\nGRAND TOTAL,, ,${grandLitres.toLocaleString('en-IN', { maximumFractionDigits: 3 })} L,${grandAmount.toFixed(2)},${grandPaid.toFixed(2)},${(grandAmount - grandPaid).toFixed(2)}\n`;
    csv += `\nGenerated by MilkBook on ${new Date().toLocaleDateString('en-IN')}\n`;

    triggerDownload(csv, filename);
}

/** Generate a PDF for a single customer — supports Monthly or Weekly. */
export async function generateIndividualPDF(customer, records, options = {}) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF('p', 'mm', 'a4');
    const { periodLabel, rate, dateRange, businessName, paymentQr, address } = options;
    const emeraldBrand = [16, 185, 129]; // #10B981
    const deepBrand = [6, 78, 59]; // #064E3B

    // 1. HEADER SECTION
    doc.setDrawColor(...emeraldBrand);
    doc.setLineWidth(0.8);
    doc.line(14, 28, 196, 28);

    doc.setTextColor(...deepBrand);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.text(businessName || 'MilkBook', 14, 20);

    doc.setTextColor(107, 114, 128);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text('Dairy Delivery & Billing Statement', 14, 25);

    doc.setTextColor(156, 163, 175);
    doc.setFontSize(10);
    const invoiceId = `Invoice #${new Date().getFullYear()}${(new Date().getMonth() + 1).toString().padStart(2, '0')}-${customer.id?.slice(-4) || '0000'}`;
    doc.text(invoiceId, 196, 20, { align: 'right' });

    const pdfCurrency = (val) => 'Rs. ' + (parseFloat(val) || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

    // 2. COMPACT 2-COLUMN CUSTOMER GRID
    const metaY = 38;
    // Column 1: Customer Details
    doc.setTextColor(156, 163, 175);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.text('BILL TO', 14, metaY);

    doc.setTextColor(17, 24, 39);
    doc.setFontSize(11);
    doc.text(customer.name.toUpperCase(), 14, metaY + 5);

    doc.setTextColor(107, 114, 128);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`+91 ${customer.phone || '—'}`, 14, metaY + 10);

    const addr = customer.address || '—';
    const splitAddr = doc.splitTextToSize(addr, 85);
    doc.setFontSize(8);
    doc.text(splitAddr, 14, metaY + 14);

    // Column 2: Billing Details
    const col2X = 115;
    const colValueX = 196;
    doc.setTextColor(156, 163, 175);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.text('BILLING INFO', col2X, metaY);

    const gridData = [
        ['PERIOD:', periodLabel.toUpperCase()],
        ['INV DATE:', new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })],
        ['RATE:', `${pdfCurrency(rate)} / L`]
    ];

    let rowY = metaY + 5;
    gridData.forEach(row => {
        doc.setTextColor(156, 163, 175);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'bold');
        doc.text(row[0], col2X, rowY);

        doc.setTextColor(17, 24, 39);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.text(row[1], colValueX, rowY, { align: 'right' });
        rowY += 5;
    });

    // 3. TWO-COLUMN DATA PREPARATION
    const leftData = [];
    const rightData = [];
    let totalLitres = 0;
    let totalAmount = 0;

    if (dateRange && dateRange.start && dateRange.end) {
        const start = new Date(dateRange.start);
        const end = new Date(dateRange.end);
        const allDays = [];
        let curr = new Date(start);
        while (curr <= end) {
            allDays.push(new Date(curr));
            curr.setDate(curr.getDate() + 1);
        }

        const mid = Math.ceil(allDays.length / 2);

        allDays.forEach((date, index) => {
            const year = date.getFullYear();
            const month = String(date.getMonth() + 1).padStart(2, '0');
            const day = String(date.getDate()).padStart(2, '0');
            const dateStr = `${year}-${month}-${day}`;

            const rec = records.find(r => r.date === dateStr);
            const rowDate = date.toLocaleDateString('en-IN', { day: '2-digit', month: 'short' });

            let row = [rowDate, '', '', '', ''];
            if (rec && !rec.no_delivery) {
                const m = parseFloat(rec.morning_qty) || 0;
                const e = parseFloat(rec.evening_qty) || 0;
                const qty = m + e;
                const rowAmt = qty * rate;
                row = [rowDate, m > 0 ? `${m}L` : '—', e > 0 ? `${e}L` : '—', qty > 0 ? `${qty.toLocaleString('en-IN', { maximumFractionDigits: 3 })}L` : '—', pdfCurrency(rowAmt)];
                totalLitres += qty;
            }

            if (index < mid) leftData.push(row);
            else rightData.push(row);
        });

        // Balance right column if shorter
        while (rightData.length < leftData.length) {
            rightData.push(['', '', '', '', '']);
        }
    }

    // 4. RENDER SIDE-BY-SIDE TABLES
    const tableY = 68;
    const tableWidth = 91; // mm
    const commonStyles = {
        fontSize: 8.5,
        cellPadding: 1.5,
        lineWidth: 0,
        textColor: [55, 65, 81]
    };
    const commonHeadStyles = {
        fillColor: null,
        textColor: emeraldBrand,
        fontStyle: 'bold'
    };
    const commonColumnStyles = {
        0: { cellWidth: 20 },
        1: { halign: 'center', cellWidth: 15 },
        2: { halign: 'center', cellWidth: 15 },
        3: { halign: 'center', fontStyle: 'bold', cellWidth: 18 },
        4: { halign: 'right', fontStyle: 'bold', cellWidth: 23 }
    };

    const drawBorders = (data) => {
        const { doc } = data;
        const { x, y, width, height } = data.cell;
        if (data.section === 'head') {
            doc.setDrawColor(...emeraldBrand);
            doc.setLineWidth(0.4);
            doc.line(x, y + height, x + width, y + height);
        } else if (data.section === 'body' && data.cell.raw !== '') {
            doc.setDrawColor(243, 244, 246);
            doc.setLineWidth(0.1);
            doc.line(x, y + height, x + width, y + height);
        }
    };

    // Left Table
    doc.autoTable({
        startY: tableY,
        margin: { left: 14 },
        tableWidth: tableWidth,
        head: [['Date', 'M', 'E', 'Qty', 'Amt']],
        body: leftData,
        theme: 'plain',
        styles: commonStyles,
        headStyles: commonHeadStyles,
        columnStyles: commonColumnStyles,
        didDrawCell: drawBorders
    });

    const leftFinalY = doc.lastAutoTable.finalY;

    // Right Table
    doc.autoTable({
        startY: tableY,
        margin: { left: 14 + tableWidth + 4 }, // 4mm gap
        tableWidth: tableWidth,
        head: [['Date', 'M', 'E', 'Qty', 'Amt']],
        body: rightData,
        theme: 'plain',
        styles: commonStyles,
        headStyles: commonHeadStyles,
        columnStyles: commonColumnStyles,
        didDrawCell: drawBorders
    });

    const finalTableY = Math.max(leftFinalY, doc.lastAutoTable.finalY);

    // 5. TOTAL SUMMARY (Full Width)
    const summaryY = finalTableY + 5;
    doc.setDrawColor(...emeraldBrand);
    doc.setLineWidth(0.6);
    doc.line(14, summaryY, 196, summaryY);

    doc.setTextColor(107, 114, 128);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text(`Bill Calculation: ${totalLitres.toLocaleString('en-IN', { maximumFractionDigits: 3 })} L x Rs. ${parseFloat(rate).toFixed(2)}`, 14, summaryY + 8);

    doc.setTextColor(...deepBrand);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    const finalCalc = totalLitres * rate;
    doc.text(`GRAND TOTAL: Rs. ${finalCalc.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`, 196, summaryY + 8, { align: 'right' });

    // 6. BOTTOM SECTION: GREETING & ADDRESS (Left) / QR (Right)
    let footerY = summaryY + 18;

    // Safety check for A4 page height (approx 297mm limit, leave margin)
    if (footerY > 235) footerY = 230;

    // Left Side (Greeting & Address)
    doc.setTextColor(...deepBrand);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Thank you for your business!', 14, footerY + 5);

    let currentLineY = footerY + 12;
    if (address) {
        doc.setTextColor(107, 114, 128);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.text('Business Details & Contact:', 14, currentLineY);
        doc.setFont('helvetica', 'normal');

        const splitContact = doc.splitTextToSize(address, 100); // Wrap inside the left half
        doc.text(splitContact, 14, currentLineY + 5);
        currentLineY += (splitContact.length * 4.5) + 6;
    }

    doc.setTextColor(107, 114, 128);
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated by MilkBook. We appreciate your support.`, 14, currentLineY + 5);

    // Right Side (Maximized QR Code directly under Grand Total)
    if (paymentQr) {
        const qrSize = 46; // Significantly larger
        const qrX = 196 - qrSize;
        const qrY = footerY;

        doc.setTextColor(156, 163, 175);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'bold');
        doc.text('SCAN TO PAY', qrX + (qrSize / 2), qrY - 2, { align: 'center' });
        try {
            doc.addImage(paymentQr, 'PNG', qrX, qrY, qrSize, qrSize);
        } catch (e) { console.error(e); }
    }

    doc.save(`${customer.name.replace(/\s+/g, '_')}_Invoice.pdf`);
}

/** Generate Overall Monthly Summary PDF. */
export async function generateSummaryPDF(data, monthLabel) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    const brandColor = [17, 24, 39]; // Clean Navy for business report

    // Background Stripe
    doc.setFillColor(...brandColor);
    doc.rect(0, 0, 210, 45, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('Business Summary Report', 14, 25);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(monthLabel.toUpperCase(), 14, 35);

    // Aggregate Calculations
    let totalLitres = 0, totalRevenue = 0, totalPaid = 0;
    data.forEach(item => {
        totalLitres += item.totals.totalLitres;
        totalRevenue += item.totals.totalAmount;
        totalPaid += (item.paidAmt || 0);
    });

    // Performance Stats Grid
    const performanceData = [
        ['GROSS REVENUE', formatCurrency(totalRevenue), 'TOTAL QUANTITY', `${totalLitres.toFixed(1)} L`],
        ['COLLECTED AMMT', formatCurrency(totalPaid), 'DUE AMOUNT', formatCurrency(totalRevenue - totalPaid)]
    ];

    doc.autoTable({
        startY: 55,
        body: performanceData,
        theme: 'grid',
        styles: {
            fontSize: 10,
            cellPadding: 6,
            textColor: [17, 24, 39]
        },
        columnStyles: {
            0: { fillColor: [249, 250, 251], fontStyle: 'bold', width: 40 },
            1: { fontStyle: 'bold', textColor: [37, 99, 235], width: 55 },
            2: { fillColor: [249, 250, 251], fontStyle: 'bold', width: 40 },
            3: { fontStyle: 'bold', width: 55 }
        }
    });

    // Breakdown Table
    const breakdown = data.map(item => [
        item.name,
        `${item.totals.totalLitres}L`,
        formatCurrency(item.totals.totalAmount),
        formatCurrency(item.paidAmt),
        formatCurrency(item.outstanding)
    ]);

    doc.setTextColor(17, 24, 39);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Customer Performance Summary', 14, doc.lastAutoTable.finalY + 15);

    doc.autoTable({
        startY: doc.lastAutoTable.finalY + 20,
        head: [['CUSTOMER', 'TOTAL QTY', 'BILL AMOUNT', 'PAID', 'OUTSTANDING']],
        body: breakdown,
        theme: 'striped',
        headStyles: {
            fillColor: [17, 24, 39],
            fontSize: 9,
            cellPadding: 4
        },
        columnStyles: {
            2: { halign: 'right' },
            3: { halign: 'right' },
            4: { halign: 'right', fontStyle: 'bold' }
        },
        bodyStyles: { fontSize: 9, cellPadding: 3 }
    });

    doc.save(`MilkBook_Full_Summary_${monthLabel.replace(/\s+/g, '_')}.pdf`);
}

function triggerDownload(content, filename) {
    const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

// Legacy window export
if (typeof window !== 'undefined') window.Reports = { downloadCustomerCSV, downloadAllCSV };
