import React, { useState, useEffect, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Download, 
  Share2, 
  ChevronRight, 
  Search, 
  FileText, 
  Wallet,
  Calendar,
  ChevronLeft,
  X,
  Phone,
  MessageCircle,
  TrendingUp,
  CreditCard,
  ArrowUpRight,
  MoreVertical,
  ArrowLeft
} from 'lucide-react';
import { useAppContext } from '../context/AppContext';
import { getMonthlySummary, updateMonthlySummary, recordPayment, MonthlySummary, cleanupCustomersBalance } from '../services/db';
import { formatCurrency, getMonthName, getPrevMonth, getNextMonth, formatDate } from '../utils/calculations';
import { generateIndividualPDF, downloadCustomerCSV } from '../utils/reports';

const Reports: React.FC = () => {
  const { customers, settings, loading, refreshCustomers } = useAppContext();
  const [selectedDate, setSelectedDate] = useState(new Date());
  const [search, setSearch] = useState('');
  const [selectedCustomer, setSelectedCustomer] = useState<any>(null);
  const [summary, setSummary] = useState<MonthlySummary | null>(null);
  const [isPayModalOpen, setIsPayModalOpen] = useState(false);
  const [paymentAmount, setPaymentAmount] = useState('');
  const [cleaning, setCleaning] = useState(false);
  const [reportStats, setReportStats] = useState({ totalBill: 0, totalCollected: 0 });
  const [statsLoading, setStatsLoading] = useState(false);

  const month = selectedDate.getMonth() + 1;
  const year = selectedDate.getFullYear();

  useEffect(() => {
    const fetchStats = async () => {
      setStatsLoading(true);
      try {
        // Recalculate monthly summaries for all customers to ensure we have the most 
        // up-to-date figures directly from the source (payments and daily records collections)
        const promises = customers.map(c => updateMonthlySummary(c.id, year, month));
        const summaries = await Promise.all(promises);
        
        let bill = 0;
        let collected = 0;
        
        summaries.forEach((s: MonthlySummary | null) => {
          if (s) {
            bill += s.current_bill || 0;
            collected += s.total_paid || 0;
          }
        });
        
        setReportStats({ totalBill: bill, totalCollected: collected });
      } catch (err) {
        console.error("Failed to fetch monthly stats", err);
      } finally {
        setStatsLoading(false);
      }
    };
    
    if (customers.length > 0) {
      fetchStats();
    }
  }, [customers, month, year]);

  const handleCleanup = async () => {
    if (!window.confirm("This will reset all negative balances (overpayments) to ₹0. Continue?")) return;
    setCleaning(true);
    await cleanupCustomersBalance();
    await refreshCustomers();
    setCleaning(false);
    alert("Balance cleanup complete. All negative entries have been fixed.");
  };

  const handlePrevMonth = () => {
    const { m, y } = getPrevMonth(month, year);
    setSelectedDate(new Date(y, m - 1));
  };

  const handleNextMonth = () => {
    const { m, y } = getNextMonth(month, year);
    setSelectedDate(new Date(y, m - 1));
  };

  const openCustomerReport = async (customer: any) => {
    setSelectedCustomer(customer);
    const summ = await getMonthlySummary(customer.id, year, month);
    setSummary(summ);
  };

  const handlePayment = async () => {
    if (!selectedCustomer || !paymentAmount || !summary) return;
    
    const amount = parseFloat(paymentAmount);
    
    // Safety restriction: Do not allow overpayment
    if (amount > summary.pending_balance) {
      alert(`Payment cannot exceed the due amount of ${formatCurrency(summary.pending_balance)}. For advanced adjustments, please contact support.`);
      return;
    }

    await recordPayment(selectedCustomer.id, {
      amount: amount,
      month,
      year,
      method: 'cash',
      date: new Date().toISOString().split('T')[0]
    });
    setIsPayModalOpen(false);
    setPaymentAmount('');
    openCustomerReport(selectedCustomer);
    refreshCustomers();
  };

  const shareOnWhatsApp = (customer: any, summ: MonthlySummary) => {
    const text = `*MilkBook Report*\n` +
      `Customer: ${customer.name}\n` +
      `Period: ${getMonthName(month)} ${year}\n` +
      `Total Qty: ${summ.total_litres} L\n` +
      `Bill: ${formatCurrency(summ.current_bill)}\n` +
      `Paid: ${formatCurrency(summ.total_paid)}\n` +
      `Due: ${formatCurrency(summ.pending_balance)}\n\n` +
      `Generated by MilkBook`;
    
    // Clean phone number (remove spaces, etc. and add country code if missing)
    const phone = customer.phone.replace(/\D/g, '');
    const mobile = phone.length === 10 ? `91${phone}` : phone;
    const url = `https://wa.me/${mobile}?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  const makeCall = (phone: string) => {
    window.location.href = `tel:${phone}`;
  };

  const exportPDF = (customer: any, summ: MonthlySummary) => {
    generateIndividualPDF(customer, summ.daily_entries, {
      periodLabel: `${getMonthName(month)} ${year}`,
      rate: settings.rate,
      dateRange: {
        start: `${year}-${String(month).padStart(2, '0')}-01`,
        end: `${year}-${String(month).padStart(2, '0')}-${new Date(year, month, 0).getDate()}`
      },
      businessName: settings.businessName,
      address: settings.address,
      paymentQr: settings.paymentQr
    });
  };

  const filteredCustomers = useMemo(() => {
    return customers.filter(c => 
      c.name.toLowerCase().includes(search.toLowerCase()) || 
      c.phone.includes(search)
    ).sort((a, b) => b.total_balance - a.total_balance);
  }, [customers, search]);

  const totalOutstanding = useMemo(() => {
    return customers.reduce((acc, c) => acc + (c.total_balance || 0), 0);
  }, [customers]);

  return (
    <div className="min-h-screen bg-gray-50/50 pb-24">
      <header className="bg-white px-5 pt-8 pb-6 border-b border-gray-100 space-y-5 rounded-b-[2.5rem] shadow-sm">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-black text-black tracking-tight">Reports</h1>
            <p className="text-[10px] text-gray-900 font-extrabold uppercase tracking-[0.2em] mt-1">Outstanding: {formatCurrency(totalOutstanding)}</p>
          </div>
          <div className="flex gap-2">
            <button 
              onClick={handleCleanup}
              disabled={cleaning}
              className="flex items-center gap-2 px-4 py-2 bg-rose-50 text-rose-700 border border-rose-100 rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-rose-100 transition-all disabled:opacity-50"
            >
              {cleaning ? "Fixing..." : "Fix Balances"}
            </button>
          </div>
        </div>

        <div className="flex items-center justify-between gap-4">
          <div className="relative group flex-1">
            <Search size={20} className="absolute left-4 top-1/2 -translate-y-1/2 text-black group-focus-within:text-blue-600 transition-colors"/>
            <input 
              type="text"
              placeholder="Search Route Records..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-12 pr-4 py-4 bg-white border border-gray-300 rounded-2xl focus:border-blue-400 focus:ring-4 focus:ring-blue-100 transition-all font-black text-black placeholder:text-gray-900/40 shadow-sm"
            />
          </div>
          
          <div className="flex items-center bg-gray-100 border border-gray-300 rounded-2xl p-1 shadow-inner shrink-0">
            <button onClick={handlePrevMonth} className="p-2 text-black hover:text-blue-600 transition-colors">
              <ChevronLeft size={20} strokeWidth={3}/>
            </button>
            <div className="px-4 text-center min-w-[120px]">
              <p className="text-[10px] font-black uppercase text-gray-600 tracking-wider leading-none">Monthly</p>
              <p className="text-sm font-black text-black mt-1">{getMonthName(month)} {year}</p>
            </div>
            <button onClick={handleNextMonth} className="p-2 text-black hover:text-blue-600 transition-colors">
              <ChevronRight size={20} strokeWidth={3}/>
            </button>
          </div>
        </div>
      </header>

      <div className="p-5 space-y-4">
        {/* Monthly Summary Hero Card */}
        <div className="bg-gradient-to-br from-indigo-700 to-blue-600 p-6 rounded-[2rem] text-white shadow-xl shadow-blue-100 relative overflow-hidden group">
          <div className="absolute -right-4 -top-4 opacity-10 group-hover:scale-110 transition-transform duration-500">
            <TrendingUp size={140} />
          </div>
          <div className="relative z-10">
            <div className="flex items-center gap-2 mb-4">
              <div className="w-8 h-8 bg-white/20 rounded-lg flex items-center justify-center backdrop-blur-md">
                <CreditCard size={16} />
              </div>
              <span className="text-xs font-black uppercase tracking-widest text-blue-100">Monthly Snapshot</span>
            </div>
            <div className="grid grid-cols-2 gap-y-6 gap-x-10">
              <div>
                <p className="text-blue-100 text-[10px] font-black uppercase tracking-widest mb-1">Total Monthly Bill</p>
                <h2 className="text-2xl font-black">{statsLoading ? '...' : formatCurrency(reportStats.totalBill)}</h2>
              </div>
              <div className="text-right">
                <p className="text-blue-100 text-[10px] font-black uppercase tracking-widest mb-1">Total Collected Bill</p>
                <h2 className="text-2xl font-black">{statsLoading ? '...' : formatCurrency(reportStats.totalCollected)}</h2>
              </div>
              <div className="pt-4 border-t border-white/10">
                <p className="text-blue-100 text-[10px] font-black uppercase tracking-widest mb-1">Overall Outstanding</p>
                <h2 className="text-xl font-black">{formatCurrency(totalOutstanding)}</h2>
              </div>
              <div className="text-right pt-4 border-t border-white/10">
                <p className="text-blue-100 text-[10px] font-black uppercase tracking-widest mb-1">Active Customers</p>
                <h2 className="text-xl font-black">{customers.length}</h2>
              </div>
            </div>
          </div>
        </div>

        <div className="pt-2">
          <h3 className="text-[10px] font-black text-gray-400 uppercase tracking-[0.2em] px-2 mb-4">Ledger Statement</h3>
          <div className="space-y-3">
            {filteredCustomers.map((c) => (
              <motion.div 
                key={c.id}
                whileTap={{ scale: 0.98 }}
                onClick={() => openCustomerReport(c)}
                className="bg-white p-5 rounded-3xl border-2 border-gray-100 shadow-md flex items-center justify-between cursor-pointer hover:border-black transition-all group active:shadow-inner"
              >
                <div className="flex items-center gap-4">
                  <div className={`w-12 h-12 rounded-2xl flex items-center justify-center font-black text-lg transition-all border-2 ${
                    c.total_balance > 0 ? 'bg-rose-100 text-rose-900 border-rose-200' : 'bg-emerald-100 text-emerald-900 border-emerald-200'
                  }`}>
                    {c.name.charAt(0)}
                  </div>
                  <div>
                    <h4 className="font-black text-black text-base">{c.name}</h4>
                    <p className="text-[11px] text-gray-900 font-black uppercase tracking-wider">{c.phone}</p>
                  </div>
                </div>
                <div className="text-right">
                  <p className="text-[9px] font-black text-gray-900 uppercase tracking-widest mb-0.5">Balance</p>
                  <div className="flex items-center gap-1.5 justify-end">
                    <p className={`font-extrabold text-base ${c.total_balance > 0 ? 'text-rose-700 font-orange-700' : 'text-emerald-700'}`}>
                      {formatCurrency(c.total_balance)}
                    </p>
                    <ArrowUpRight size={14} strokeWidth={3} className="text-black group-hover:text-blue-600" />
                  </div>
                </div>
              </motion.div>
            ))}

            {filteredCustomers.length === 0 && (
              <div className="py-20 text-center">
                <div className="w-20 h-20 bg-gray-100 rounded-[2.5rem] flex items-center justify-center mx-auto mb-4">
                  <Search size={32} className="text-gray-300" />
                </div>
                <p className="text-gray-400 font-bold uppercase text-[10px] tracking-widest px-10 leading-relaxed">No customers match your search criteria</p>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Modern Detailed Report Modal */}
      <AnimatePresence>
        {selectedCustomer && (
          <div className="fixed inset-0 z-[100] flex items-end sm:items-center justify-center p-0 lg:p-4">
            <motion.div 
              initial={{opacity:0}} 
              animate={{opacity:1}} 
              exit={{opacity:0}} 
              onClick={()=>setSelectedCustomer(null)} 
              className="absolute inset-0 bg-gray-900/60 backdrop-blur-md"
            />
            <motion.div 
              initial={{y:'100%'}} 
              animate={{y:0}} 
              exit={{y:'100%'}} 
              transition={{ type: "spring", damping: 25, stiffness: 200 }}
              className="relative w-full max-w-lg bg-white rounded-t-[3rem] sm:rounded-[3rem] shadow-[0_-20px_40px_rgba(0,0,0,0.1)] max-h-[92vh] flex flex-col pointer-events-auto"
            >
              {summary ? (
                <div className="overflow-y-auto no-scrollbar pb-10">
                  {/* Sticky Modal Header */}
                  <div className="sticky top-0 bg-white/80 backdrop-blur-xl z-20 px-8 py-6 border-b border-gray-50 flex items-center justify-between">
                    <div className="flex items-center gap-4">
                      <button onClick={()=>setSelectedCustomer(null)} className="p-2 bg-gray-50 rounded-xl text-gray-400 hover:text-gray-900 transition-colors">
                        <ArrowLeft size={20} />
                      </button>
                      <div>
                        <h2 className="text-2xl font-black text-gray-900 leading-tight">{selectedCustomer.name}</h2>
                        <div className="flex items-center gap-2 mt-1">
                          <span className="text-[10px] font-black text-blue-600 uppercase tracking-widest">{getMonthName(month)} {year}</span>
                          <span className="w-1 h-1 bg-gray-200 rounded-full"/>
                          <span className="text-[10px] font-black text-gray-400 uppercase tracking-widest">Report</span>
                        </div>
                      </div>
                    </div>
                    <div className="flex gap-2">
                       <button onClick={()=>makeCall(selectedCustomer.phone)} className="w-11 h-11 bg-blue-50 text-blue-600 rounded-2xl flex items-center justify-center active:scale-90 transition-all shadow-sm">
                        <Phone size={18} fill="currentColor" />
                      </button>
                      <button onClick={()=>shareOnWhatsApp(selectedCustomer, summary)} className="w-11 h-11 bg-emerald-50 text-emerald-600 rounded-2xl flex items-center justify-center active:scale-90 transition-all shadow-sm">
                        <MessageCircle size={20} fill="currentColor" />
                      </button>
                    </div>
                  </div>

                  <div className="p-8 space-y-8">
                    {/* Financial Summary Pane */}
                    <div className="grid grid-cols-2 gap-4">
                      <div className="bg-gray-900 p-6 rounded-[2rem] text-white">
                        <p className="text-[10px] text-gray-400 font-extrabold uppercase tracking-widest mb-1">Month Bill</p>
                        <h3 className="text-2xl font-black">{formatCurrency(summary.current_bill)}</h3>
                      </div>
                      <div className="bg-blue-600 p-6 rounded-[2rem] text-white">
                        <p className="text-[10px] text-blue-100 font-extrabold uppercase tracking-widest mb-1">Total Paid</p>
                        <h3 className="text-2xl font-black">{formatCurrency(summary.total_paid)}</h3>
                      </div>
                      <div className="bg-rose-600 p-6 rounded-[2rem] text-white">
                        <p className="text-[10px] text-rose-100 font-extrabold uppercase tracking-widest mb-1">Pending Due</p>
                        <h3 className="text-2xl font-black">{formatCurrency(summary.pending_balance)}</h3>
                      </div>
                      <div className="bg-gray-100 p-6 rounded-[2rem] text-gray-900">
                        <p className="text-[10px] text-gray-500 font-extrabold uppercase tracking-widest mb-1">Total Qty</p>
                        <h3 className="text-2xl font-black">{summary.total_litres} <span className="text-sm font-medium">L</span></h3>
                      </div>
                    </div>

                    {/* Monthly Record & Payment Log */}
                    <div className="space-y-4">
                      <div className="flex items-center justify-between px-1">
                        <h4 className="text-[10px] font-black uppercase text-gray-400 tracking-[0.2em]">Monthly Record & Payments</h4>
                        <div className={`px-3 py-1 rounded-full text-[9px] font-black uppercase tracking-widest ${
                          summary.status === 'paid' ? 'bg-emerald-50 text-emerald-600' : 'bg-rose-50 text-rose-600'
                        }`}>
                          {summary.status}
                        </div>
                      </div>

                      <div className="bg-gray-50 rounded-[2.5rem] p-4 space-y-3 border border-blue-50/50">
                        {/* Inline Payment Collection Field */}
                        {summary.pending_balance > 0 && (
                          <div className="bg-white p-5 rounded-3xl shadow-sm border-2 border-emerald-100 space-y-4">
                            <div className="flex items-center gap-3">
                              <div className="w-10 h-10 bg-emerald-50 text-emerald-600 rounded-xl flex items-center justify-center">
                                <Wallet size={20} />
                              </div>
                              <div>
                                <p className="text-xs font-black text-gray-800">Quick Pay</p>
                                <p className="text-[10px] text-gray-400 font-bold uppercase">Record Payment Inline</p>
                              </div>
                            </div>
                            <div className="flex gap-2">
                              <div className="relative flex-1">
                                <span className="absolute left-4 top-1/2 -translate-y-1/2 font-black text-gray-400">₹</span>
                                <input 
                                  type="number" 
                                  placeholder="0.00"
                                  value={paymentAmount}
                                  onChange={(e)=>setPaymentAmount(e.target.value)}
                                  className="w-full pl-9 pr-4 py-3 bg-gray-50 border border-gray-200 rounded-2xl focus:bg-white focus:border-emerald-300 transition-all font-black text-lg outline-none"
                                />
                              </div>
                              <button 
                                onClick={handlePayment}
                                className="px-6 py-3 bg-emerald-600 text-white rounded-2xl font-black text-xs uppercase tracking-widest active:scale-95 transition-all shadow-lg shadow-emerald-100"
                              >
                                Record
                              </button>
                            </div>
                          </div>
                        )}

                        {/* Combined Log List (Deliveries & Payments) */}
                        {(() => {
                          const combinedLogs = [
                            ...summary.daily_entries.map(e => ({ ...e, logType: 'delivery' })),
                            ...(summary.payments || []).map(p => ({ ...p, logType: 'payment' }))
                          ].sort((a, b) => b.date.localeCompare(a.date));

                          if (combinedLogs.length === 0) {
                            return <div className="py-10 text-center text-gray-400 text-xs font-bold uppercase tracking-widest italic opacity-40">No entries saved for this month</div>;
                          }

                          return combinedLogs.map((item: any, idx) => (
                            <div key={item.id || item.date + idx} className={`flex items-center justify-between py-4 px-5 rounded-2xl shadow-sm border transition-all hover:scale-[1.02] ${
                              item.logType === 'payment' ? 'bg-emerald-50 border-emerald-100' : 'bg-white border-gray-100/50'
                            }`}>
                              <div className="flex items-center gap-4">
                                <div className={`w-9 h-9 rounded-xl flex flex-col items-center justify-center border ${
                                  item.logType === 'payment' 
                                    ? 'bg-emerald-600 text-white border-emerald-700' 
                                    : 'bg-gray-50 text-gray-600 border-gray-100'
                                }`}>
                                  <span className="text-[8px] font-black uppercase leading-none">{formatDate(item.date, 'short').split(' ')[1]}</span>
                                  <span className="text-sm font-black mt-0.5 leading-none">{formatDate(item.date, 'short').split(' ')[0]}</span>
                                </div>
                                <div>
                                  {item.logType === 'payment' ? (
                                    <>
                                      <p className="text-xs font-black text-emerald-800 tracking-tight">Payment Received</p>
                                      <p className="text-[10px] text-emerald-600/60 font-bold uppercase">Cash Settlement</p>
                                    </>
                                  ) : (
                                    <>
                                      <p className="text-xs font-black text-gray-800 tracking-tight">{item.total_litres} Litres</p>
                                      <p className="text-[10px] text-gray-400 font-bold uppercase">Delivery Log</p>
                                    </>
                                  )}
                                </div>
                              </div>
                              <div className="text-right">
                                <p className={`text-sm font-black ${item.logType === 'payment' ? 'text-emerald-700' : 'text-gray-900'}`}>
                                  {item.logType === 'payment' ? `- ${formatCurrency(item.amount)}` : formatCurrency(item.daily_amount)}
                                </p>
                                {item.no_delivery && <span className="text-[8px] text-rose-500 font-black uppercase">Skipped</span>}
                              </div>
                            </div>
                          ));
                        })()}
                      </div>
                    </div>

                    {/* Quick Access Exports */}
                    <div className="space-y-4">
                       <h4 className="text-[10px] font-black uppercase text-gray-400 tracking-[0.2em] pl-1">Export Documents</h4>
                       <div className="grid grid-cols-2 gap-3">
                         <button onClick={()=>exportPDF(selectedCustomer, summary)} className="flex items-center gap-3 p-4 bg-white border border-gray-100 rounded-3xl group hover:border-blue-500 hover:bg-blue-50/10 transition-all">
                            <div className="w-10 h-10 bg-rose-50 text-rose-600 rounded-xl flex items-center justify-center group-hover:bg-rose-600 group-hover:text-white transition-all shadow-sm">
                              <FileText size={18} />
                            </div>
                            <div className="text-left">
                              <p className="text-xs font-black text-gray-900">PDF Bill</p>
                              <p className="text-[10px] text-gray-400 font-bold tracking-tight">Generate Invoice</p>
                            </div>
                         </button>
                         <button onClick={()=>downloadCustomerCSV(selectedCustomer, summary.daily_entries, month, year, settings.rate)} className="flex items-center gap-3 p-4 bg-white border border-gray-100 rounded-3xl group hover:border-emerald-500 hover:bg-emerald-50/10 transition-all">
                            <div className="w-10 h-10 bg-emerald-50 text-emerald-600 rounded-xl flex items-center justify-center group-hover:bg-emerald-600 group-hover:text-white transition-all shadow-sm">
                              <Download size={18} />
                            </div>
                            <div className="text-left">
                              <p className="text-xs font-black text-gray-900">CSV Sheet</p>
                              <p className="text-[10px] text-gray-400 font-bold tracking-tight">Master Ledger</p>
                            </div>
                         </button>
                       </div>
                    </div>
                  </div>
                </div>
              ) : (
                <div className="p-24 text-center space-y-4 bg-white rounded-t-[3rem]">
                   <div className="w-16 h-16 bg-blue-50 rounded-3xl flex items-center justify-center text-blue-600 animate-bounce mx-auto">
                    <TrendingUp size={32} />
                  </div>
                  <p className="text-gray-400 font-black uppercase text-[10px] tracking-[0.3em] animate-pulse">Calculating Statement...</p>
                </div>
              )}
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default Reports;
