import { formatCurrency, getMonthName } from './calculations';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

// ─────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────
const EMERALD: [number, number, number] = [16, 185, 129];
const DEEP:    [number, number, number] = [6, 78, 59];

const pdfCurrency = (val: any) =>
  (parseFloat(val) || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

// ─────────────────────────────────────────────────────────────
// QR image loader (canvas-based, 5s timeout, no CORS issues)
// ─────────────────────────────────────────────────────────────
const getBase64Image = (url: string): Promise<string> => {
  return new Promise((resolve) => {
    const timer = setTimeout(() => resolve(''), 5000);
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      clearTimeout(timer);
      try {
        const canvas = document.createElement('canvas');
        canvas.width = img.naturalWidth || 200;
        canvas.height = img.naturalHeight || 200;
        const ctx = canvas.getContext('2d');
        if (!ctx) { resolve(''); return; }
        ctx.drawImage(img, 0, 0);
        resolve(canvas.toDataURL('image/png'));
      } catch (_e) { resolve(''); }
    };
    img.onerror = () => { clearTimeout(timer); resolve(''); };
    img.src = url + (url.includes('?') ? '&' : '?') + '_t=' + Date.now();
  });
};

// ─────────────────────────────────────────────────────────────
// CSV helpers
// ─────────────────────────────────────────────────────────────

export function downloadCustomerCSV(customer: any, records: any[], month: number, year: number, rate: number) {
  const monthName = getMonthName(month);
  const filename = `MilkBook_${(customer.name || 'customer').replace(/\s+/g, '_')}_${monthName}_${year}.csv`;

  let csv = `MilkBook — Milk Delivery Report\n`;
  csv += `Customer: ${customer.name}\nPhone: ${customer.phone || '—'}\nPeriod: ${monthName} ${year}\n\n`;
  csv += `Date,Day,Session,Quantity (L),Rate,Amount (₹)\n`;

  const sorted = [...records].sort((a, b) => a.date.localeCompare(b.date));
  let totalLitres = 0, totalAmount = 0;

  for (const rec of sorted) {
    if (rec.no_delivery) continue;
    const d = new Date(rec.date);
    const dayName = d.toLocaleDateString('en-IN', { weekday: 'short' });
    if (rec.morning_qty > 0)
      csv += `${rec.date},${dayName},Morning,${rec.morning_qty},${rec.rate_per_litre || rate},${(rec.morning_qty * (rec.rate_per_litre || rate)).toFixed(2)}\n`;
    if (rec.evening_qty > 0)
      csv += `${rec.date},${dayName},Evening,${rec.evening_qty},${rec.rate_per_litre || rate},${(rec.evening_qty * (rec.rate_per_litre || rate)).toFixed(2)}\n`;
    totalLitres += (parseFloat(rec.total_litres) || 0);
    totalAmount += (parseFloat(rec.daily_amount) || 0);
  }

  csv += `\nTOTAL,,, ${totalLitres.toLocaleString('en-IN', { maximumFractionDigits: 3 })} L,, ${totalAmount.toFixed(2)}\n`;
  csv += `\nGenerated by MilkBook on ${new Date().toLocaleDateString('en-IN')}\n`;
  triggerDownload(csv, filename);
}

export function downloadAllCSV(allData: any[], month: number, year: number) {
  const monthName = getMonthName(month);
  const filename = `MilkBook_Summary_${monthName}_${year}.csv`;
  let csv = `MilkBook Business Summary — ${monthName} ${year}\n\n`;
  csv += `Customer Name,Phone,Days Delivered,Total Litres,Gross Bill (₹),Paid (₹),Outstanding (₹)\n`;

  let grandLitres = 0, grandAmount = 0, grandPaid = 0;
  for (const row of allData) {
    csv += `"${row.name}","${row.phone || '—'}",${row.totals.daysDelivered},${row.totals.totalLitres},${row.totals.totalAmount.toFixed(2)},${row.totalPaid.toFixed(2)},${row.accountBalance.toFixed(2)}\n`;
    grandLitres += row.totals.totalLitres;
    grandAmount += row.totals.totalAmount;
    grandPaid += row.totalPaid;
  }
  csv += `\nGRAND TOTAL,, ,${grandLitres.toLocaleString('en-IN', { maximumFractionDigits: 3 })} L,${grandAmount.toFixed(2)},${grandPaid.toFixed(2)},${(grandAmount - grandPaid).toFixed(2)}\n`;
  csv += `\nGenerated by MilkBook on ${new Date().toLocaleDateString('en-IN')}\n`;
  triggerDownload(csv, filename);
}

// ─────────────────────────────────────────────────────────────
// PDF drawing helpers
// ─────────────────────────────────────────────────────────────

function drawInvoiceHeader(doc: jsPDF, businessName: string, month: number, year: number, customerId: string) {
  doc.setFillColor(249, 250, 251);
  doc.rect(0, 0, 210, 35, 'F');
  doc.setDrawColor(EMERALD[0], EMERALD[1], EMERALD[2]);
  doc.setLineWidth(1.5);
  doc.line(0, 35, 210, 35);

  doc.setTextColor(DEEP[0], DEEP[1], DEEP[2]);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(26);
  doc.text(businessName || 'MilkBook', 14, 18);

  doc.setTextColor(107, 114, 128);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Dairy Delivery & Billing Statement', 14, 26);

  const invoiceId = `Invoice #${year}${String(month).padStart(2, '0')}-${(customerId || '').slice(-4) || '0000'}`;
  doc.setTextColor(156, 163, 175);
  doc.setFontSize(10);
  doc.text(invoiceId, 196, 18, { align: 'right' });
}

function drawBillingMeta(doc: jsPDF, customer: any, periodLabel: string, rate: number) {
  const metaY = 42;

  doc.setTextColor(156, 163, 175); doc.setFontSize(7); doc.setFont('helvetica', 'bold');
  doc.text('BILL TO', 14, metaY);
  doc.setTextColor(17, 24, 39); doc.setFontSize(14); doc.setFont('helvetica', 'bold');
  doc.text((customer.name || '').toUpperCase(), 14, metaY + 6);
  doc.setTextColor(107, 114, 128); doc.setFontSize(10); doc.setFont('helvetica', 'normal');
  doc.text(`+91 ${customer.phone || '—'}`, 14, metaY + 12);

  const col2X = 135, colValueX = 196;
  doc.setTextColor(156, 163, 175); doc.setFontSize(7); doc.setFont('helvetica', 'bold');
  doc.text('BILLING INFO', col2X, metaY);

  const gridData = [
    ['PERIOD:', periodLabel.toUpperCase()],
    ['INV DATE:', new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })],
    ['RATE:', `Rs. ${pdfCurrency(rate)} / L`]
  ];

  let rowY = metaY + 6;
  for (const [label, value] of gridData) {
    doc.setTextColor(156, 163, 175); doc.setFontSize(8); doc.setFont('helvetica', 'bold');
    doc.text(label, col2X, rowY);
    doc.setTextColor(17, 24, 39); doc.setFontSize(11); doc.setFont('helvetica', 'bold');
    doc.text(value, colValueX, rowY, { align: 'right' });
    rowY += 6;
  }
}

function buildTableData(records: any[], month: number, year: number, rate: number) {
  const leftData: string[][] = [];
  const rightData: string[][] = [];
  let totalLitres = 0;

  // new Date(year, month, 0) with 1-based month gives last day of that month
  const lastDay = new Date(year, month, 0).getDate();
  const mid = Math.ceil(lastDay / 2);
  const monthShort = getMonthName(month).slice(0, 3);

  for (let d = 1; d <= lastDay; d++) {
    const dateStr = `${year}-${String(month).padStart(2, '0')}-${String(d).padStart(2, '0')}`;
    const rec = records.find(r => r.date === dateStr);
    const rowDate = `${String(d).padStart(2, '0')} ${monthShort}`;

    let row: string[] = [rowDate, '', '', '', ''];
    if (rec && !rec.no_delivery) {
      const qM = parseFloat(rec.morning_qty) || 0;
      const qE = parseFloat(rec.evening_qty) || 0;
      const qty = qM + qE;
      if (qty > 0) {
        row = [rowDate, qM > 0 ? `${qM}L` : '—', qE > 0 ? `${qE}L` : '—', `${qty}L`, `Rs. ${pdfCurrency(qty * rate)}`];
        totalLitres += qty;
      }
    }
    if (d <= mid) leftData.push(row);
    else rightData.push(row);
  }

  while (rightData.length < leftData.length) rightData.push(['', '', '', '', '']);
  return { leftData, rightData, totalLitres };
}

function drawDailyTables(doc: jsPDF, leftData: string[][], rightData: string[][]): number {
  const tableY = 75;
  const tableWidth = 91;

  const commonStyles = { fontSize: 9, cellPadding: 2, lineWidth: 0, textColor: [55, 65, 81] as [number, number, number] };
  const commonHeadStyles = { fillColor: false as any, textColor: EMERALD, fontStyle: 'bold' as const };
  const commonColumnStyles = {
    0: { cellWidth: 20 },
    1: { halign: 'center' as const, cellWidth: 15 },
    2: { halign: 'center' as const, cellWidth: 15 },
    3: { halign: 'center' as const, fontStyle: 'bold' as const, cellWidth: 18 },
    4: { halign: 'right' as const, fontStyle: 'bold' as const, cellWidth: 23 }
  };

  const drawHeaders = (data: any) => {
    if (data.section === 'head') {
      const { doc: d, cell } = data;
      d.setDrawColor(EMERALD[0], EMERALD[1], EMERALD[2]);
      d.setLineWidth(0.5);
      d.line(cell.x, cell.y, cell.x + cell.width, cell.y);
      d.line(cell.x, cell.y + cell.height, cell.x + cell.width, cell.y + cell.height);
    }
  };

  autoTable(doc, {
    startY: tableY, margin: { left: 14 }, tableWidth,
    head: [['Date', 'M', 'E', 'Qty', 'Amt']],
    body: leftData, theme: 'plain', styles: commonStyles,
    headStyles: commonHeadStyles, columnStyles: commonColumnStyles,
    didDrawCell: drawHeaders
  });

  const leftFinalY = (doc as any).lastAutoTable.finalY;

  autoTable(doc, {
    startY: tableY, margin: { left: 14 + tableWidth + 4 }, tableWidth,
    head: [['Date', 'M', 'E', 'Qty', 'Amt']],
    body: rightData, theme: 'plain', styles: commonStyles,
    headStyles: commonHeadStyles, columnStyles: commonColumnStyles,
    didDrawCell: drawHeaders
  });

  return Math.max(leftFinalY, (doc as any).lastAutoTable.finalY);
}

function drawSummary(doc: jsPDF, summaryY: number, totalLitres: number, rate: number, oldBalance: number, grandTotal: number) {
  doc.setDrawColor(EMERALD[0], EMERALD[1], EMERALD[2]);
  doc.setLineWidth(0.8);
  doc.line(14, summaryY, 196, summaryY);

  doc.setTextColor(107, 114, 128); doc.setFontSize(10); doc.setFont('helvetica', 'bold');
  doc.text(`Bill Calculation: ${totalLitres.toFixed(1)} L x Rs. ${pdfCurrency(rate)}`, 14, summaryY + 8);
  if (oldBalance > 0)
    doc.text(`(Plus Old Balance: Rs. ${pdfCurrency(oldBalance)})`, 14, summaryY + 14);

  doc.setTextColor(DEEP[0], DEEP[1], DEEP[2]); doc.setFontSize(18); doc.setFont('helvetica', 'bold');
  doc.text(`GRAND TOTAL: Rs. ${pdfCurrency(grandTotal)}`, 196, summaryY + 9, { align: 'right' });
}

async function drawFooter(
  doc: jsPDF, footerY: number,
  address: string | undefined, businessName: string,
  paymentQr: string | undefined, upiId: string | undefined, grandTotal: number
) {
  doc.setTextColor(DEEP[0], DEEP[1], DEEP[2]); doc.setFontSize(14); doc.setFont('helvetica', 'bold');
  doc.text('Thank you for your business!', 14, footerY + 5);

  doc.setTextColor(107, 114, 128); doc.setFontSize(10); doc.setFont('helvetica', 'bold');
  doc.text('Business Details & Contact:', 14, footerY + 13);

  if (address) {
    doc.setFont('helvetica', 'normal'); doc.setFontSize(10);
    doc.text(doc.splitTextToSize(address, 100), 14, footerY + 18);
  }

  doc.setTextColor(156, 163, 175); doc.setFontSize(8);
  doc.text('Generated by MilkBook. We appreciate your support.', 14, 286);

  const qrSize = 50;
  const qrX = 196 - qrSize;
  const qrY = footerY + 2;

  let qrSrc = paymentQr || '';
  if (upiId && grandTotal > 0) {
    const upiUrl = `upi://pay?pa=${upiId}&pn=${encodeURIComponent(businessName || 'MilkBook')}&am=${grandTotal.toFixed(2)}&cu=INR&tn=Milk%20Bill`;
    qrSrc = `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(upiUrl)}`;
  }

  if (qrSrc) {
    doc.setTextColor(156, 163, 175); doc.setFontSize(9); doc.setFont('helvetica', 'bold');
    doc.text('SCAN TO PAY', qrX + qrSize / 2, qrY - 2, { align: 'center' });
    try {
      const b64 = qrSrc.startsWith('http') ? await getBase64Image(qrSrc) : qrSrc;
      if (b64) doc.addImage(b64, 'PNG', qrX, qrY, qrSize, qrSize);
    } catch (_e) { /* skip QR silently */ }
  }
}

// ─────────────────────────────────────────────────────────────
// Public PDF API
// ─────────────────────────────────────────────────────────────

/** Generate and download a PDF bill for a single customer. */
export async function generateIndividualPDF(customer: any, records: any[], options: any = {}) {
  const {
    periodLabel = '',
    rate = 0,
    businessName = 'MilkBook',
    paymentQr,
    upiId,
    address,
    oldBalance = 0,
    totalBalance,
    month: optMonth,
    year: optYear,
    dateRange
  } = options;

  // Resolve month/year — prefer explicit params, fall back to dateRange
  let month: number = optMonth;
  let year: number = optYear;
  if ((!month || !year) && dateRange?.start) {
    const parts = (dateRange.start as string).split('-');
    year = parseInt(parts[0]);
    month = parseInt(parts[1]);
  }
  if (!month) month = new Date().getMonth() + 1;
  if (!year)  year  = new Date().getFullYear();

  const doc = new jsPDF('p', 'mm', 'a4');

  drawInvoiceHeader(doc, businessName, month, year, customer.id);
  drawBillingMeta(doc, customer, periodLabel, rate);

  const { leftData, rightData, totalLitres } = buildTableData(records || [], month, year, rate);
  const finalTableY = drawDailyTables(doc, leftData, rightData);

  const summaryY = finalTableY + 8;
  const grandTotal = totalBalance != null ? totalBalance : totalLitres * rate;
  drawSummary(doc, summaryY, totalLitres, rate, oldBalance, grandTotal);

  let footerY = summaryY + 22;
  if (footerY > 240) { doc.addPage(); footerY = 20; }

  await drawFooter(doc, footerY, address, businessName, paymentQr, upiId, grandTotal);

  if (options.save !== false) {
    doc.save(`${(customer.name || 'Customer').replace(/\s+/g, '_')}_Bill_${periodLabel.replace(/\s+/g, '_')}.pdf`);
  }
  
  return doc;
}

/** Generate a single PDF with one invoice per page for all customers. */
export async function generateBulkInvoicesPDF(customersWithSummaries: any[], options: any) {
  const { periodLabel, rate, businessName, paymentQr, upiId, address, month, year } = options;
  if (!customersWithSummaries.length) return;

  const doc = new jsPDF('p', 'mm', 'a4');

  for (let i = 0; i < customersWithSummaries.length; i++) {
    const { customer, summary } = customersWithSummaries[i];
    if (i > 0) doc.addPage();

    const monthlyBill = summary.current_bill   || 0;
    const monthlyPaid = summary.total_paid     || 0;
    const netBalance  = customer.total_balance || 0;
    const oldBalance  = Math.max(0, netBalance - (monthlyBill - monthlyPaid));

    drawInvoiceHeader(doc, businessName, month, year, customer.id);
    drawBillingMeta(doc, customer, periodLabel, rate);

    const entries = summary.daily_entries || [];
    const { leftData, rightData, totalLitres } = buildTableData(entries, month, year, rate);
    const finalTableY = drawDailyTables(doc, leftData, rightData);

    const summaryY = finalTableY + 8;
    drawSummary(doc, summaryY, totalLitres, rate, oldBalance, netBalance);

    let footerY = summaryY + 22;
    if (footerY > 240) footerY = 240;

    await drawFooter(doc, footerY, address, businessName, paymentQr, upiId, netBalance);
  }

  doc.save(`MilkBook_All_Bills_${periodLabel.replace(/\s+/g, '_')}.pdf`);
}

/** Generate an overall monthly summary PDF. */
export async function generateSummaryPDF(data: any[], monthLabel: string) {
  const doc = new jsPDF();

  doc.setFillColor(17, 24, 39);
  doc.rect(0, 0, 210, 45, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22); doc.setFont('helvetica', 'bold');
  doc.text('Business Summary Report', 14, 25);
  doc.setFontSize(12); doc.setFont('helvetica', 'normal');
  doc.text(monthLabel.toUpperCase(), 14, 35);

  let totalLitres = 0, totalRevenue = 0, totalPaid = 0;
  data.forEach(item => {
    totalLitres  += item.totals.totalLitres;
    totalRevenue += item.totals.totalAmount;
    totalPaid    += (item.totalPaid || 0);
  });

  autoTable(doc, {
    startY: 55,
    body: [
      ['GROSS REVENUE', formatCurrency(totalRevenue), 'TOTAL QUANTITY', `${totalLitres.toFixed(1)} L`],
      ['COLLECTED AMMT', formatCurrency(totalPaid), 'DUE AMOUNT', formatCurrency(totalRevenue - totalPaid)]
    ],
    theme: 'grid',
    styles: { fontSize: 10, cellPadding: 6, textColor: [17, 24, 39] as [number, number, number] },
    columnStyles: {
      0: { fillColor: [249, 250, 251] as [number, number, number], fontStyle: 'bold', cellWidth: 40 },
      1: { fontStyle: 'bold', textColor: [37, 99, 235] as [number, number, number], cellWidth: 55 },
      2: { fillColor: [249, 250, 251] as [number, number, number], fontStyle: 'bold', cellWidth: 40 },
      3: { fontStyle: 'bold', cellWidth: 55 }
    }
  });

  const breakdown = data.map(item => [
    item.name, `${item.totals.totalLitres}L`,
    formatCurrency(item.totals.totalAmount),
    formatCurrency(item.totalPaid),
    formatCurrency(item.accountBalance)
  ]);

  doc.setTextColor(17, 24, 39); doc.setFontSize(14); doc.setFont('helvetica', 'bold');
  doc.text('Customer Performance Summary', 14, (doc as any).lastAutoTable.finalY + 15);

  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 20,
    head: [['CUSTOMER', 'TOTAL QTY', 'BILL AMOUNT', 'PAID', 'ACCT BALANCE']],
    body: breakdown, theme: 'striped',
    headStyles: { fillColor: [17, 24, 39] as [number, number, number], fontSize: 9, cellPadding: 4 },
    columnStyles: { 2: { halign: 'right' }, 3: { halign: 'right' }, 4: { halign: 'right', fontStyle: 'bold' } },
    bodyStyles: { fontSize: 9, cellPadding: 3 }
  });

  doc.save(`MilkBook_Full_Summary_${monthLabel.replace(/\s+/g, '_')}.pdf`);
}

// ─────────────────────────────────────────────────────────────

function triggerDownload(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  document.body.removeChild(a); URL.revokeObjectURL(url);
}
